name: flappy_bird
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flame: ^1.13.1
  firebase_auth: ^4.13.0
  sizer: ^2.0.15
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  flame_audio: ^2.1.6
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: Game
      fonts:
        - asset: assets/fonts/Game.ttf
